name: Build frontend image

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build-containers:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v1
      with:
        node-version: '15.5'
       
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}   
      run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    # Build backend services
    - name: Build backend
      run: |
        docker build ./frontend/ -t zefryuuko/pse-frontend:latest
    
    # Push to Docker Hub
    - name: Push to Docker Hub
      run: |
        docker push zefryuuko/pse-frontend:latest
    
    # TODO: kickstart pull new image on host
